server:
  port: 8081
  compression: 
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://192.168.0.166:3306/robot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: root
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    password: gzz123
